export const macHeroImgs = [
  {
    id: 1,
    img: "https://i.ibb.co/pd2RFtz/macbook-air-f6z1e32o3866-medium.jpg",
    New: 'New',
    title: "Macbook Air 15''",
    subTitle: "Impressively big. Impossibly thin.",
    price: "From $108.25/mo. for 12 mo. or $1299",
    link: "apple.com",
    width: "984px",
    height: "184px",
  },
  {
    id: 2,
    img: "https://i.ibb.co/PcrRd7G/mac-studio-c2wojtx43pw2-large.jpg",
    New: "New",
    title: "Mac Studio",
    subTitle: "Supercharged by M2 Max and M2 Ultra.",
    price: "From $166.58/mo. for 12 mo. or $1999",
    link: "apple.com",
    marginTop: "120px",
    width: "542px",
    height: "256px"
  },
  {
    id: 4,
    img: "https://i.ibb.co/4WWs6GG/mac-pro-zkewy14r84iq-large.jpg",
    New: "New",
    title: "Mac Pro",
    subTitle: "Transformed by Apple silicon.",
    price: "From $583.25/mo. for 12 mo. or $6999",
    link: "apple.com",
    marginTop: "120px",
    width: "622px",
    height: "392px",
  },
];